feat (consent-survey): Automatic redirect to target survey
GSA-TTS/identity-idva-qualtrics pull request #78
Opened 2024-01-05 16:30 UTC by nathan-moore-97

2024-01-05 19:43 UTC, dzaslavskiy commented on qualtrix/client.py
> +    return response
what is this change?

2024-01-05 20:04 UTC, dzaslavskiy requested changes
refactor qualtrics api calls into seperate reusable functions

2024-01-06 00:24 UTC, nathan-moore-97 commented on qualtrix/client.py
> +    return response
No idea. Ill put it back

2024-01-08 18:37 UTC, dzaslavskiy approved these changes

2024-01-08 18:37 UTC, merged